### ISSUE TITLE
Use workbox when not using cdn service

### ISSUE THREAD

**Issue by liuyuchenzh** [liuyuchenzh/y-cli#3]
Add `workbox-webpack-plugin` to production when no cdn service is being used.

[Details](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin)

**Comment by huangxiaolu** [comment]
[support sw using workbox-webpack-plugin](https://github.com/liuyuchenzh/y-cli/commit/f5bab0a2166ca7a70f487ac08a6bfbca6a204bcf)
